name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
   contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: pwsh -File generate_readme.ps1
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Geoffrey Muchugi
          author_email: geoffreymuchugi@appsavvytalk.com
          
          

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: sleep 3

